language: generic
env:
  - COMPILER=smlnj PACKAGES="smlnj ml-yacc ml-ulex moreutils"
  - COMPILER=mlton PACKAGES="mlton moreutils"
before_install:
  - sudo add-apt-repository -y ppa:matthew.fluet/mlton
  - sudo apt-get update -qq
  - sudo apt-get install -y --force-yes ${PACKAGES}
install:
  - git submodule init
  - git submodule update --init --recursive
script:
  - ./script/test-${COMPILER}.sh

notifications:
  email: false
